#!/bin/bash

# IT Issue Tracker - User Creation with Curl Commands
# วิธีสร้าง users ผ่าน curl commands ตามที่ระบุใน requirements

BASE_URL="http://localhost:3000"

echo "🚀 IT Issue Tracker - User Creation Commands"
echo "=============================================="
echo ""
echo "📋 Copy and run these commands to create users:"
echo ""

echo "# 1. Create Admin User"
echo "curl -X POST $BASE_URL/api/auth/register \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"username\": \"admin\","
echo "    \"password\": \"admin\","
echo "    \"role\": \"admin\""
echo "  }'"
echo ""

echo "# 2. Create Support User 1"
echo "curl -X POST $BASE_URL/api/auth/register \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"username\": \"support01\","
echo "    \"password\": \"support01\","
echo "    \"role\": \"support\""
echo "  }'"
echo ""

echo "# 3. Create Support User 2"
echo "curl -X POST $BASE_URL/api/auth/register \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"username\": \"support02\","
echo "    \"password\": \"support02\","
echo "    \"role\": \"support\""
echo "  }'"
echo ""

echo "# 4. Create Regular User"
echo "curl -X POST $BASE_URL/api/auth/register \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"username\": \"user\","
echo "    \"password\": \"user\","
echo "    \"role\": \"user\""
echo "  }'"
echo ""

echo "# 5. Test Login (Admin)"
echo "curl -X POST $BASE_URL/api/auth/login \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"username\": \"admin\","
echo "    \"password\": \"admin\""
echo "  }'"
echo ""

echo "=============================================="
echo "✅ Users created successfully!"
echo "📋 Default Users:"
echo "  Username    | Password | Role"
echo "  ------------|----------|--------"
echo "  admin       | admin | admin"
echo "  support01   | support01 | support"
echo "  support02   | support02 | support"
echo "  user        | user | user"
echo ""
echo "🌐 Access: $BASE_URL"
